### PR TITLE
New scoreboard for round and overall stats

### PR DESCRIPTION
**Pull request by tylers-dev**
Scoreboard will show player scores for that round as well as overall all time score.

### CODE REVIEW

**Comment by AgentRev** [comment]
@tylers-dev: lol I hope my `#define` frenzy didn't give you too much of a headache

**Comment by tylers-dev** [comment]
Screenshot of the new scoreboard
https://dl.dropboxusercontent.com/u/27371339/20160410200744_1.jpg

**Comment by tylers-dev** [comment]
@AgentRev No it actually worked well for me. Setting the defines to always be relative to each other. So everything wasn't some absolute positioned nightmare.

**Comment by AgentRev** [comment]
Yeah it looks like a complicated mess at first glance, but it's designed to make minor adjustments a lot easier once you get the hang of it. I spent like 3 days hand-coding the whole thing without any testing/previews/sketches; got it working right within an hour after completion. Many think I'm crazy.

**Comment by codexGW** [comment]
Nice!

**Comment by codexGW** [comment]
I was worried about conflicts when I saw this. It's just one more thing to keep a close eye on during merges :frowning: . Right now your persistent scoreboard option in the main config doesn't even work with sock so I hope that doesn't cause any issues too. I think this setup would be best if used when the persistent scoreboard option is set to 0 or maybe add this as a new option for vanilla.

**Pull request merged**
