### PR TITLE
Bounty system

### PR DESCRIPTION
**Pull request by tylers-dev**
System to pay for putting bounties on enemy players. Payment integrated
in current ATM. Bounties display in Scoreboard. Persistence to store
bounty kills and prevent groups from collecting each other's bounties.

### CODE REVIEW

**Comment by AgentRev** [comment]
at first glance, I would say this looks pretty decent :+1:

**Comment by tylers-dev** [comment]
You'd cry if you knew how long it took me. But I learned a lot.

**Comment by tylers-dev** [comment]
Oh and worth noting, it's not exactly extDB working. Once we're up and running I can work it in, but the sock db is all I've got to test right now.

**Comment by AgentRev** [comment]
that'd be like a 10-min edit really... just a couple of fields

**Comment by Masiin** [comment]
Agent, what would be the edit to make it work with extDB?

**Comment by AgentRev** [comment]
Adding the fields to the database structure, writing them in the loading and saving procedure, etc...

**Pull request merged**
