### PR TITLE
Allow snipers and divers the ability to heal

### PR DESCRIPTION
**Pull request by tylers-dev**
Seems better to allow everyone the fair chance to buy a medkit and heal themselves with it.

### CODE REVIEW

**Comment by codexGW** [comment]
What about the starting uniforms and diving gear? Did you test this? I needs to work for op4 blu4 and ind.

**Comment by tylers-dev** [comment]
I did test this. I got the ghilli when I spawned as sniper, i got the wetsuit when I spawned as diver. The getDefaultClothing.sqf already did all this proper assigning of uniform/vest/items to snipers and divers. I just made it define _isSniper and _isDiver to the description we set in the mission.sqm rather than the class unit type. That way they can technically be medics (to heal themselves), but still get assigned the same gear they were getting before.

**Comment by codexGW** [comment]
Nice. Let give it a go. If you tested it that good enough for me.

**Comment by tylers-dev** [comment]
Excellent

**Pull request merged**
