### PR TITLE
Custom loading screen image

### PR DESCRIPTION
**Pull request by MrNastyTime**
Not sure if I'm doing this right but hey might as well at least try something. This is to add a custom image to the initial loading screen when you first join the server. Just thought it would add another unique thing to it. You can view the image I put together here:

http://postimg.org/image/9xnkhvnx7/

Credit for this code from Wiking @ Arma Junkies.

### CODE REVIEW

**Comment by AgentRev** [comment]
The text is barely readable and the fact that you used a default screenshot from the store page is a bit cringey.

**Comment by MrNastyTime** [comment]
Yeah, that's why I didn't add the image to the commit. I'd figure I would toss something out there and just see. But I will try to make something else later, BBQ time now. I'm trying here, I got a better idea for later. Thanks for the input. Anyone else feels like throwing something in go for it.

**Comment by mooneymoon** [comment]
It's a good idea. I'll try to work something up later.

**Comment by MrNastyTime** [comment]
http://postimg.org/image/8spdnehpn/

**Comment by codexGW** [comment]
I couldn't get this to work. I even dl the AJ pbo because they don't seem to have a github anymore and wiking deleted his or made it private. Some community's just don't understand what A3W is about and they should just start over with their own wasteland if they want to base their work off of Agents and team wasteland but make it private. Here my attempted image.
loading

**Pull request closed without merging**
